// WordMemo v10 runtime patch — evidence-based learning engine
(function(){
const TRANSLATION_OVERRIDES={'of':'связь / принадлежность: «чашка чая», «часть чего-то»','to':'к, в направлении; перед глаголом — частица инфинитива','in':'внутри; в каком-то месте / периоде','for':'для; ради; на протяжении времени','on':'на поверхности; о теме; в определённый день','with':'с кем-то / чем-то; при помощи чего-то','at':'в конкретной точке / месте; в конкретное время','from':'из / от: источник, начало движения или отправитель','by':'рядом; с помощью; кем/чем выполнено действие','about':'о чём-то; примерно / около','into':'внутрь, с движением внутрь','over':'над; через; больше чем; в течение','after':'после; вслед за','before':'до; перед','under':'под; ниже; в условиях / под контролем','between':'между двумя или несколькими объектами','around':'вокруг; примерно; по разным местам','through':'через / сквозь; на протяжении процесса','against':'против; у / вплотную к поверхности','without':'без','within':'внутри; в пределах времени / границ','across':'через, с одной стороны на другую','off':'с поверхности; прочь; выключено','up':'вверх; выше; до завершения (во фразовых глаголах)','down':'вниз; ниже; до меньшего уровня','out':'наружу; вне; полностью / до конца во фразовых глаголах'};
for(const w of WORDS){const x=TRANSLATION_OVERRIDES[w.en.toLowerCase()];if(x)w.ru=x}
const V10_VERSION='10.0';
const PREPOSITIONS=new Set(['of','to','in','for','on','with','at','from','by','about','into','over','after','before','under','between','around','through','against','without','within','across','off','up','down','out']);
const FUNCTION_WORDS=new Set(['the','a','an','and','or','but','if','so','as','that','which','who','what','when','where','why','how','this','these','those','some','any','each','every','all','both','either','neither']);
const VISUAL_GROUPS=[
{icon:'👤',words:'person people man woman boy girl child baby adult somebody someone anyone everybody mother father parent brother sister family friend student teacher doctor patient manager worker employee agent judge president'.split(' ')},
{icon:'🏠',words:'home house room apartment building door window floor kitchen hotel office school hospital restaurant store shop bank church station airport city town village street road park area place country'.split(' ')},
{icon:'🚗',words:'car bus train plane flight vehicle road travel trip journey drive ride traffic'.split(' ')},
{icon:'📱',words:'phone computer internet technology machine camera television radio screen message email video'.split(' ')},
{icon:'📚',words:'book paper article magazine story report letter word language english information education lesson class study test question answer'.split(' ')},
{icon:'💼',words:'work job business company office meeting project plan service market money cost price pay account contract'.split(' ')},
{icon:'🍽️',words:'food water coffee tea drink meal dinner lunch breakfast restaurant cup glass'.split(' ')},
{icon:'🌿',words:'tree plant flower animal dog cat bird horse sea river water earth nature environment'.split(' ')},
{icon:'❤️',words:'love heart feeling smile happy happiness care relationship friend family'.split(' ')},
{icon:'⏰',words:'time day week month year morning night hour minute moment today tomorrow yesterday'.split(' ')},
{icon:'🏃',words:'go come move walk run sit stand leave arrive travel drive carry bring take put hold turn stop start begin continue'.split(' ')},
{icon:'💬',words:'say tell speak talk ask answer call explain discuss conversation communication'.split(' ')},
{icon:'👀',words:'see look watch show view read notice appear'.split(' ')},
{icon:'🧠',words:'know think understand remember learn believe mean idea mind reason decide consider'.split(' ')},
{icon:'🛠️',words:'make do use build create develop change improve replace fix produce'.split(' ')},
{icon:'⚖️',words:'law legal right rule court judge decision evidence'.split(' ')},
{icon:'🌍',words:'world country nation government community society public international'.split(' ')},
{icon:'🎵',words:'music song sound voice art film movie picture image'.split(' ')},
{icon:'⚽',words:'game sport play team ball win lose'.split(' ')}];
const VISUAL_LOOKUP=new Map();for(const g of VISUAL_GROUPS)for(const x of g.words)VISUAL_LOOKUP.set(x,g.icon);
const PREP_CORE={of:'Показывает связь между существительными. Часто по-русски отдельный предлог вообще не нужен: a cup of tea → «чашка чая».',to:'Движение к цели: go to work. Перед глаголом to часто не предлог, а частица инфинитива: want to learn.',in:'Что-то находится внутри пространства/периода: in the bag, in July.',on:'Контакт с поверхностью или тема/день: on the table, on Monday, a book on history.',at:'Точка, а не пространство: at the station, at 7 o’clock.',for:'Цель/получатель или длительность: for you, for two hours.',from:'Источник или начальная точка: from Anna, from London.',by:'Способ/автор/рядом: by bus, written by her, by the door.',with:'Совместность или инструмент: with my brother, cut with a knife.',about:'Тема или приблизительность: talk about work, about ten minutes.',into:'Движение внутрь: walk into the room.',over:'Над/через/больше: over the table, over 100 people.',under:'Ниже/под: under the table.',between:'В промежутке между объектами: between two houses.',through:'Сквозь/через процесс: through the window, through the night.',around:'Вокруг или примерно: around the park, around five o’clock.',against:'Против или с контактом: against the wall.',without:'Отсутствие: without sugar.',across:'С одной стороны на другую: across the street.',off:'С поверхности / отключение: take it off, turn it off.',up:'Направление вверх; во фразовых глаголах смысл меняется: get up, pick up.',down:'Направление вниз; во фразовых глаголах: sit down, write down.',out:'Наружу / вне; во фразовых глаголах: go out, find out.'};
function inferVisual(w){const en=w.en.toLowerCase();if(PREPOSITIONS.has(en))return{kind:'prep',icon:'',title:'Пространственная схема',note:PREP_CORE[en]||'Смотрите на роль слова в конкретной фразе.'};if(FUNCTION_WORDS.has(en))return{kind:'function',icon:'🔗',title:'Служебное слово',note:'Запоминайте не отдельный перевод, а функцию слова в предложении.'};const icon=VISUAL_LOOKUP.get(en);if(icon)return{kind:'semantic',icon,title:'Визуальная ассоциация',note:'Свяжите слово с образом, затем закройте перевод и назовите слово самостоятельно.'};if(VERB_LEMMAS.has(en))return{kind:'semantic',icon:'🎬',title:'Действие / процесс',note:'Представьте короткую сцену, в которой кто-то выполняет это действие.'};return{kind:'semantic',icon:'🧩',title:'Смысловой якорь',note:'Свяжите слово с конкретной ситуацией из примера, а не только с русским переводом.'}}
function visualMemoryHtml(w){const v=inferVisual(w),en=w.en.toLowerCase();if(v.kind==='prep'){const cls=['in','on','under','over','to','from','with','between'].includes(en)?'prep-'+en:'prep-in';return `<div class="visual-memory prep"><div class="visual-title">${escapeHTML(w.en)} · ${escapeHTML(v.title)}</div><div class="prep-scene ${cls}"><div class="prep-box"></div><div class="prep-dot"></div></div><div class="visual-note">${escapeHTML(v.note)}</div></div>`}return `<div class="visual-memory"><div class="visual-icon" aria-hidden="true">${v.icon}</div><div class="visual-title">${escapeHTML(v.title)}</div><div class="visual-note">${escapeHTML(v.note)}</div></div>`}
function prepUsageHtml(w){const x=PREP_CORE[w.en.toLowerCase()];return x?`<div class="preposition-note"><b>Как понимать в живой речи:</b> ${escapeHTML(x)}</div>`:''}
function fisherYates(arr){arr=[...arr];for(let i=arr.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[arr[i],arr[j]]=[arr[j],arr[i]]}return arr}
function ensureV10State(){state.updatedAt=state.updatedAt||Date.now();state.recentIds=Array.isArray(state.recentIds)?state.recentIds:[];state.settings=state.settings||{};state.settings.mode='random';state.engine=state.engine||{version:V10_VERSION}}ensureV10State();
const IDB_NAME='wordmemo-v10',IDB_STORE='state',IDB_KEY='main';
function openWordMemoDB(){return new Promise((resolve,reject)=>{if(!('indexedDB'in window))return reject(new Error('IndexedDB unavailable'));const r=indexedDB.open(IDB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(IDB_STORE))r.result.createObjectStore(IDB_STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function idbWrite(snapshot){try{const db=await openWordMemoDB();await new Promise((resolve,reject)=>{const tx=db.transaction(IDB_STORE,'readwrite');tx.objectStore(IDB_STORE).put(snapshot,IDB_KEY);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close()}catch(e){console.warn('WordMemo IndexedDB write:',e)}}
async function idbRead(){try{const db=await openWordMemoDB();const val=await new Promise((resolve,reject)=>{const tx=db.transaction(IDB_STORE,'readonly');const r=tx.objectStore(IDB_STORE).get(IDB_KEY);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error)});db.close();return val}catch(e){return null}}
save=function(){state.updatedAt=Date.now();state.engine={version:V10_VERSION};try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true}catch(e){storageOK=false}idbWrite(JSON.parse(JSON.stringify(state)));updateSaveIndicator()};
function updateSaveIndicator(){const el=document.getElementById('saveStateText');if(el)el.textContent=storageOK?'Сохранено на этом устройстве':'Ошибка локального сохранения';const dot=document.getElementById('saveStateDot');if(dot)dot.classList.toggle('warn',!storageOK)}
async function recoverPersistentState(){const dbState=await idbRead();if(dbState&&dbState.version===1&&(dbState.updatedAt||0)>(state.updatedAt||0)){state=dbState;ensureV10State();try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){}applyTheme();render(currentPage);toast('Прогресс восстановлен из резервного хранилища устройства')}try{if(navigator.storage&&navigator.storage.persist)await navigator.storage.persist()}catch(e){}updateSaveIndicator()}
buildSession=function(){const now=Date.now(),h=historyToday(),pool=selectedWords(),recent=new Set((state.recentIds||[]).slice(-60));let due=pool.filter(w=>{const c=state.cards[w.id];return c&&c.status!=='new'&&c.due<=now});due=fisherYates(due);let allowed=Math.max(0,state.settings.newPerDay-(h.new||0));let unseen=pool.filter(w=>!state.cards[w.id]||state.cards[w.id].status==='new');let preferred=unseen.filter(w=>!recent.has(w.id)),fallback=unseen.filter(w=>recent.has(w.id));let fresh=fisherYates(preferred).concat(fisherYates(fallback)).slice(0,allowed);let arr=[],d=[...due],f=[...fresh];while(d.length||f.length){if(d.length)arr.push(d.shift());if(f.length)arr.push(f.shift());if(d.length&&Math.random()<.4)arr.push(d.shift())}return arr};
const SCIENCE_INTERVALS=[0,1,3,7,14,30,60,120];
rate=function(q){const w=session[sessionIndex],c=cardState(w.id),wasNew=c.status==='new',now=Date.now();if(lastTypedCorrect===false&&q>1)q=1;c.stage=Number.isFinite(c.stage)?c.stage:Math.min(c.reps||0,SCIENCE_INTERVALS.length-1);c.last=now;if(q===0){c.lapses=(c.lapses||0)+1;c.stage=Math.max(0,c.stage-1);c.reps=Math.max(0,(c.reps||0)-1);c.interval=0;c.due=now+2*MIN;c.status='learning'}else if(q===1){c.stage=Math.max(1,c.stage);c.reps=(c.reps||0)+1;c.interval=c.stage<=1?0:SCIENCE_INTERVALS[c.stage-1];c.due=c.stage<=1?now+10*MIN:now+c.interval*DAY;c.status='learning'}else{c.stage=Math.min(SCIENCE_INTERVALS.length-1,c.stage+(q===3?2:1));c.reps=(c.reps||0)+1;c.interval=SCIENCE_INTERVALS[c.stage];c.due=now+c.interval*DAY;c.status='learning'}const k=todayKey();if(!state.history[k])state.history[k]={reviews:0,again:0,hard:0,good:0,easy:0,new:0};const hh=state.history[k];hh.reviews++;hh[['again','hard','good','easy'][q]]++;if(wasNew)hh.new++;state.recentIds=(state.recentIds||[]).concat(w.id).slice(-120);if((wasNew||q===0||lastTypedCorrect===false)&&session.length<80){const lag=2+Math.floor(Math.random()*3),pos=Math.min(session.length,sessionIndex+1+lag);session.splice(pos,0,w)}save();sessionIndex++;revealed=false;attemptRecorded=false;lastTypedCorrect=null;renderStudy()};
previewInterval=function(c,q){const stage=Number.isFinite(c.stage)?c.stage:Math.min(c.reps||0,SCIENCE_INTERVALS.length-1);if(q===0)return'2 мин';if(q===1)return stage<=1?'10 мин':SCIENCE_INTERVALS[Math.max(1,stage-1)]+' дн';const next=Math.min(SCIENCE_INTERVALS.length-1,stage+(q===3?2:1));return SCIENCE_INTERVALS[next]+' дн'};
const baseRenderStudy=renderStudy;renderStudy=function(){baseRenderStudy();if(!session.length||sessionIndex>=session.length)return;const w=session[sessionIndex],mode=currentMode==='teacher'?teacherModeFor(w):currentMode;if(mode==='cards'){const answer=document.getElementById('answer');if(answer&&!answer.querySelector('.visual-memory')){const holder=document.createElement('div');holder.innerHTML=visualMemoryHtml(w)+prepUsageHtml(w);answer.insertBefore(holder,answer.firstChild)}}const head=document.querySelector('#page-study .session-head');if(head&&!head.querySelector('.save-state'))head.insertAdjacentHTML('beforeend',`<span class="save-state"><i id="saveStateDot" class="save-dot ${storageOK?'':'warn'}"></i><span id="saveStateText">${storageOK?'Сохранено':'Ошибка сохранения'}</span></span>`)};
const baseCheckRecall=checkRecall;checkRecall=function(){baseCheckRecall();setTimeout(renderStudyVisualOnly,0)};const baseCheckContext=checkContext;checkContext=function(){baseCheckContext();setTimeout(renderStudyVisualOnly,0)};
function renderStudyVisualOnly(){if(!session.length||sessionIndex>=session.length)return;const w=session[sessionIndex],box=document.querySelector('#page-study .example-box:not(.hidden)');if(box&&!box.querySelector('.visual-memory'))box.insertAdjacentHTML('beforeend',visualMemoryHtml(w)+prepUsageHtml(w))}
const baseWordLibraryDetail=wordLibraryDetail;wordLibraryDetail=function(w){let html=baseWordLibraryDetail(w),needle='<div class="example-box">',insert=visualMemoryHtml(w)+prepUsageHtml(w),idx=html.indexOf(needle);return idx>=0?html.slice(0,idx)+insert+html.slice(idx):insert+html};
renderHome=function(){const c=counts(),h=historyToday(),foundation=WORDS.slice(0,500).filter(w=>statusOf(state.cards[w.id])==='mastered').length,bridge=WORDS.slice(500).filter(w=>statusOf(state.cards[w.id])==='mastered').length,due=c.due,newLeft=Math.max(0,(state.settings.newPerDay||10)-(h.new||0));document.getElementById('page-home').innerHTML=pageHeader('Сегодня','Короткая сессия с активным вспоминанием, интервалами и контекстом.')+`<div class="science-hero"><h2>${due?'Продолжим с повторений':'Готовы к новой порции слов?'}</h2><p>Сначала вспоминаем, затем получаем обратную связь и возвращаем слово через увеличивающиеся интервалы. Новые слова перемешиваются.</p><div class="today-strip"><div class="today-metric"><b>${due}</b><span>повторить сейчас</span></div><div class="today-metric"><b>${newLeft}</b><span>новых доступно</span></div><div class="today-metric"><b>${c.m}</b><span>устойчиво освоено</span></div></div><div class="actions"><button class="btn primary big" onclick="startStudy('teacher')">Начать умную сессию</button><button class="btn" data-page="library">Библиотека</button></div></div><div class="panel"><h2>Как устроено запоминание</h2><div class="method-steps"><div class="method-step"><b>1 · Смысл + образ</b><small>Пример, произношение и визуальный якорь.</small></div><div class="method-step"><b>2 · Вспоминание</b><small>Достаём слово из памяти, а не перечитываем.</small></div><div class="method-step"><b>3 · Контекст</b><small>Вставляем слово в живую фразу.</small></div><div class="method-step"><b>4 · Интервалы</b><small>Минуты → дни → недели.</small></div></div></div><div class="panel"><h2>Прогресс</h2><div class="sub">A1–A2 foundation: <b>${foundation}/500</b> · A2–B1 bridge: <b>${bridge}/500</b></div><div class="progress" style="margin-top:14px"><i style="width:${Math.round(c.m/10)}%"></i></div><div class="save-state" style="margin-top:12px"><i id="saveStateDot" class="save-dot ${storageOK?'':'warn'}"></i><span id="saveStateText">${storageOK?'Прогресс автоматически сохраняется на этом устройстве':'Есть проблема с локальным сохранением'}</span></div></div>`};
const baseRenderSettings=renderSettings;renderSettings=function(){baseRenderSettings();const root=document.querySelector('#page-settings .settings');if(root){const sync=document.createElement('div');sync.className='field sync-card';sync.innerHTML=`<label>Синхронизация iPhone ↔ компьютер</label><div class="sync-status"><div class="sync-icon">☁️</div><div><b>Облачная синхронизация — следующий инфраструктурный этап</b><p>Эта версия уже дублирует локальный прогресс в localStorage + IndexedDB. Для настоящей синхронизации между устройствами нужен backend и идентификация пользователя; GitHub Pages сам по себе только раздаёт статические файлы.</p></div></div><div class="notice">Я не буду хранить секретный GitHub-токен внутри браузера ради псевдосинхронизации — это небезопасно.</div>`;root.insertBefore(sync,root.firstChild)}updateSaveIndicator()};
state.settings.mode='random';save();render(currentPage);recoverPersistentState();
})();
